import 'package:quizz_app/src/models/catagories_model.dart';
import 'package:quizz_app/src/models/question_model.dart';

List<Category> categories = [
  Category(
    'History',
    'history.jpg',
    [
      Question('Was Julius Caesar assassinated on the Ides of March?', true),
      Question('Did the American Civil War end in 1870?', false),
      Question('Is Cleopatra known as the last pharaoh of Egypt?', true),
      Question('Did World War II end in 1945?', true),
      Question('Was the Great Wall of China built during the Ming Dynasty?', true),
      Question('Did the Roman Empire fall in 476 AD?', true),
      Question('Did Marco Polo discover America?', false),
      Question('Was Napoleon exiled to the island of Elba?', true),
      Question('Did the Industrial Revolution begin in the 20th century?', false),
      Question('Was the Berlin Wall demolished in 1991?', false),
    ],
  ),
  Category(
    'Culture',
    'culture.jpeg',
    [
      Question('Is sushi originally from Japan?', true),
      Question('Do people celebrate Diwali in Brazil?', false),
      Question('Is the Louvre Museum located in Paris, France?', true),
      Question('Does Flamenco music originate from Germany?', false),
      Question('Is the Tango a traditional dance from Argentina?', true),
      Question('Is Oktoberfest a beer festival from Austria?', false),
      Question('Do people in China celebrate the Lunar New Year?', true),
      Question('Is reggae music native to Jamaica?', true),
      Question('Do the Maori people originate from New Zealand?', true),
      Question('Is Bastille Day a national holiday in Canada?', false),
    ],
  ),
  Category(
    'Math',
    'math.jpeg',
    [
      Question('Is 5 a prime number?', true),
      Question('Is the square root of 64 equal to 6?', false),
      Question('Is 0 considered an even number?', true),
      Question('Does 3 + 5 equal 10?', false),
      Question('Is the number pi approximately 3.14?', true),
      Question('Does 7 multiplied by 8 equal 56?', true),
      Question('Is 2 a composite number?', false),
      Question('Does 9 divided by 3 equal 2?', false),
      Question('Is the sum of angles in a triangle always 180 degrees?', true),
      Question('Is 15 a multiple of 4?', false),
    ],
  ),
  Category(
    'Geography',
    'geography.jpeg',
    [
      Question('Is Mount Everest the highest peak in the world?', true),
      Question('Is the Amazon River the longest river on Earth?', false),
      Question('Is Australia both a country and a continent?', true),
      Question('Does the Sahara Desert cover most of Europe?', false),
      Question('Is Africa the largest continent by area?', false),
      Question('Is Tokyo the capital of Japan?', true),
      Question('Is the Great Barrier Reef located off the coast of France?', false),
      Question('Does the Nile River flow through Egypt?', true),
      Question('Is Greenland an independent country?', false),
      Question('Is the capital of Canada Ottawa?', true),
    ],
  ),
  Category(
    'Science',
    'science.jpg',
    [
      Question('Is the chemical symbol for water H2O?', true),
      Question('Does the sun revolve around the Earth?', false),
      Question('Is the speed of light faster than the speed of sound?', true),
      Question('Is Pluto still classified as a planet?', false),
      Question('Do humans have 46 chromosomes in their cells?', true),
      Question('Is DNA the blueprint of life?', true),
      Question('Can energy be created or destroyed according to the law of conservation?', false),
      Question('Does Earth have three moons?', false),
      Question('Is gravity responsible for keeping us on the ground?', true),
      Question('Is helium a heavier element than oxygen?', false),
    ],
  ),
];
